version: '2'
services:
  bitcannon_front:
    build: ./web
    image: bitcannon_front
    container_name: bitcannon_front
    ports:
      - "80:9000"
  bitcannon_api:
    build: ./api
    image: bitcannon_api
    container_name: bitcannon_api
    links:
      - mongo
      - bitcannon_front
    ports:
      - "8000:1337"
  mongo: 
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
# create a named datavolume
volumes:  
    db_data: